### PR TITLE
BA for Tensorflow

### PR DESCRIPTION
**Pull request by maggiehollis**
Implementation of [BA](https://github.com/microsoft/ADBench/blob/master/src/python/modules/Tensorflow/TensorflowBA.py) for TensorFlow

### CODE REVIEW

**Review by samestep — CHANGES_REQUESTED** [review]
Thanks for doing this! One step closer to parity with ADBench :)

Similar to #103, this implementation is failing the validation added in #101; see [the CI logs](https://github.com/gradbench/gradbench/actions/runs/11731154326/job/32681277625?pr=110). If you look at the full log, you can see that the reason the `assert a == b` check is failing is because the TensorFlow tool implementation is simply returning `"output": "Process terminated due to timeout."`; is there a way to fix this?

**Comment by maggiehollis** [comment]
I reverted the merge from main because it presented a new issue with diffsharp?

**Comment by athas** [comment]
That's a transient issue with DiffSharp, which is flaky. It's unrelated to any changes in the main branch.

**Comment by samestep** [comment]
The commit c45de3903c8108d2d0a91ac4640630e5739653ec seems to have messed up the Git history so I'm force-pushing to 437b6de89521974f8b9469aeb554bf068827f0dc.

**Review by samestep — CHANGES_REQUESTED** [review]
Seems to be working now that the timeout is removed! @maggiehollis would you be able to remove the commented-out timeout code? Then this should be ready to merge.

**Review by samestep — APPROVED** [review]
Looks good, thanks Maggie!

**Pull request merged**
