### PR TITLE
Implement MyGrad

### PR DESCRIPTION
**Pull request by maggiehollis**

### CODE REVIEW

**Comment by maggiehollis** [comment]
Not sure what the issue is - works on my computer and the x86 locally.

**Comment by maggiehollis** [comment]
NumPy 2.0 was released yesterday (6/16) and has some updates that aren't supported. Fixed it by specifying last NumPy version (1.26.0)

**Comment by samestep** [comment]
Yeah I saw the NumPy 2.0 announcement pop up on Hacker News and immediately thought "oh shit, this is gonna break some things :("

**Review by samestep — APPROVED** [review]
Great work!

**Pull request merged**
